plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"aimaid-devrun" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

	runs {
		client {
			programArg "--username"
			programArg "MaidDev"

			programArg "--uuid"
			programArg "11111111-1111-1111-1111-111111111111"
		}
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	def aiMaid = "io.github.ozozorz.aimaid:ai-maid:${project.aimaid_version}"
	def testAddon = "io.github.ozozorz.aimaid:testaddon:${project.testaddon_version}"

	implementation aiMaid
	clientImplementation aiMaid

	implementation testAddon
	clientImplementation testAddon
}


tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}
